# Generated by Django 4.1.5 on 2023-01-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact_number',
            field=models.CharField(default=7870218634, max_length=15),
            preserve_default=False,
        ),
    ]
